### ISSUE TITLE
bug fixes for v3.2

### ISSUE THREAD

**Issue by bora-7** [firozt/InterviewStartPage#39]
some feedback for bug fixes from discord and friends. they are mostly nitpicks but that's a good sign. If there's more I'll add it as comments to this issue

leaderboards component:
- center the box, make it big from the start

difficulty component:
- the number of total questions solved isn't centered when it's a 2 digit or a single digit number. 

search bar:
- emre said the colour of the text on the search bar isn't really visible

recent submissions:
- the name on the drop down should be recently solved or something, because it's not submissions it's correct submissions.

interviews:
- set default deadline to one day in the future
- capitalise the R in remove in prev components
- add comment section in previous interviews, also store this in localStorage

todays question:
- make it more clear that the question is todays daily, like akina sent (i dm'd it to rooge the pic is there)

general:
- have input box come up on the screen instead of a text directing them to settings if the username is not cached

**Comment by bora-7** [comment]
make the json filename for descriptive (rn it's settings.json, but we can make it like "leettab-<timestamp>.json" which would be a lot more useful.

**Comment by firozt** [comment]
finished most issues, issues not done has been moved to v4
